version: '3'
services:
  app:
    build: .
    ports:
      - "1234:8080"
    links:
      - mysql
    volumes:
      - ".:/go/src/github.com/rni-hamada/yohiho"

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/etc/mysql/conf.d/master.cnf

volumes:
  mysql-data:
